[package]
name = "lrcat-extractor"
version = "0.1.0"
authors = ["Hubert Figuière <hub@figuiere.net>"]
edition = "2018"

[dependencies]
chrono = "0.4.0"
peg = { version = "0.6.0" }
rusqlite = { version = "0.25" }
try_opt = "0.1.1"

docopt = { version = "0.8.1", optional = true }
serde = { version = "1.0.15", optional = true }
serde_derive = { version = "1.0", optional = true }  # if you're using `derive(Deserialize)`

[lib]
name = "lrcat"

[[bin]]
name = "dumper"
required-features = ["binaries"]

[features]
binaries = ["docopt", "serde", "serde_derive" ]
