[package]
name = "lrcat-extractor"
version = "0.1.0"
authors = ["Hubert Figuière <hub@figuiere.net>"]

[dependencies]
chrono = "0.4.0"
docopt = "0.8.1"
rusqlite = "0.12.0"

[lib]
name = "lrcat"

[[bin]]
name = "dumper"
